server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polygraphy
    username: polygraphy
    password: polygraphy

mail:
   username: polygraphy.polygraphy@gmail.com
   password: gjkbuhfabz
   protocol: smtp
   host: smtp.gmail.com
   port: 587
   charset: UTF-8
   smtp:
       auth: true
       starttls:
           enable: true
           required: true
       debug: true
logging.path: ~/spring